My_First_Project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls'))

]

first_app/urls.py
from django.conf.urls import url
from django.urls import path
from first_app import views

app_name = "first_app"

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('musician_details/<pk>/', views.MusicianDetail.as_view(),
         name='musician_details'),
    path('add_musician/', views.AddMusician.as_view(), name='add_musician'),
    path('musician_update/<pk>/', views.UpdateMusician.as_view(),
         name='musician_update'),
    path('musician_delete/<pk>/', views.DeletMusician.as_view(),
         name='musician_delete'),
]

first_app/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Musician(models.Model):
    # id = models.AutoField(Primary_key=True)
    first_name = models.CharField("Name Of First", max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=100)

    def __str__(self):
        return self.first_name + " " + self.last_name

    def get_absolute_url(self):
        return reverse('first_app:musician_details', kwargs={'pk': self.pk})


class Album(models.Model):
    # id = models.AutoField(Primary_key=True)
    artist = models.ForeignKey(
        Musician, on_delete=models.CASCADE, related_name='album_list')
    name = models.CharField(max_length=100)
    release_date = models.DateField()
    rating = (
        (1, "Worst"),
        (2, "Bad"),
        (3, "Not Bad"),
        (4, "Good"),
        (5, "Excelent"),
    )
    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name + ", Rating: " + str(self.num_stars)

first_app/forms.py
from django import forms
from first_app import models


class MusicianForm(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = "__all__"


class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))
    name = forms.CharField(label='Name Of Album')

    class Meta:
        model = models.Album
        fields = "__all__"

first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from first_app import models
from django.urls import reverse_lazy

# Create your views here.


class IndexView(ListView):
    context_object_name = 'musician_list'
    model = models.Musician
    template_name = 'first_app/index.html'


class MusicianDetail(DetailView):
    context_object_name = 'musician'
    model = models.Musician
    template_name = 'first_app/musician_details.html'


class AddMusician(CreateView):
    fields = ('first_name', 'last_name', 'instrument')
    model = models.Musician
    template_name = 'first_app/musician_form.html'


class UpdateMusician(UpdateView):
    fields = ('first_name', 'last_name', 'instrument')
    model = models.Musician
    template_name = 'first_app/musician_form.html'


class DeletMusician(DeleteView):
    context_object_name = 'musician'
    model = models.Musician
    success_url = reverse_lazy("first_app:index")
    template_name = 'first_app/delete_musician.html'

first_app/templates/first_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <title> </title>
</head>

<body>
  <nav class="navbar navbar-expand-sm bg-dark navbar-light_blue">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'first_app:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'first_app:add_musician' %}">Add Musician</a>
      </li>

    </ul>
  </nav>

  <div class="container" style="padding-top: 20px">
    {% block body_block %}

    {% endblock %}
  </div>

</body>

</html>

first_app/templates/first_app/delete_musician.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<h3>Delete {{musician.first_name}} {{musician.last_name}}?</h3>
<form method="POST">
  {% csrf_token %}
  <input type="submit" name="submit" value="Delete" class="btn btn-danger btn-sm"> <a href="{% url 'first_app:musician_details' pk=musician.pk %}" class="btn btn-info btn-sm">Cancel</a>
</form>
{% endblock %}

first_app/templates/first_app/index.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<ul>
  {% for musician in musician_list %}
  <li> <a href="{% url 'first_app:musician_details' pk=musician.pk %}">{{ musician.first_name }} {{ musician.last_name }}</a> </li>
  {% endfor %}
</ul>
{% endblock %}

first_app/templates/first_app/musician_details.html
{% extends 'first_app/base.html' %}
{% block body_block %}
<h3>Musician Details:</h3>
<p>{{musician.first_name}} {{musician.last_name}}</p>
<p>{{musician.instrument}}</p>
<h3>Album</h3>
<ul>
  {% for album in musician.album_list.all %}
  <li>{{ album.name }}</li>
  {% endfor %}
</ul>
<a href="{% url 'first_app:musician_update' pk=musician.pk %}" class="btn btn-warning btn-sm">Update</a>
<br>
<a href="{% url 'first_app:musician_delete' pk=musician.pk %}" class="btn btn-danger btn-sm">Delete</a>
{% endblock %}

first_app/templates/first_app/musician_form.html
{% extends 'first_app/base.html' %}
{% block body_block %}
{% if form.instance.pk %}
<h3>Update Musician</h3>
{% else %}
<h3>Add New Musician</h3>
{% endif %}
<form method="POST">
  {{ form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Add" class="btn btn-info btn-sm">
</form>
{% endblock %}